# Generated by Django 4.0.5 on 2022-07-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembukuan',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
