# Generated by Django 4.0.6 on 2022-07-12 06:41

import email
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan', '0003_details'),
    ]

    def insert_default_details(apps, schema_editor):
        Details = apps.get_model('pembukuan', 'details')
        Details_push = Details(name='', pemilik='', email='', phone=0, field='', address='', city='')
        Details_push.save()

    operations = [
        migrations.RunPython(insert_default_details)
    ]

