# Generated by Django 4.0.6 on 2022-07-12 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan', '0004_auto_20220712_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembukuan',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pembukuan.details'),
            preserve_default=False,
        ),
    ]
