# Generated by Django 4.0.6 on 2022-07-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan', '0006_alter_details_options_alter_pembukuan_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={},
        ),
    ]
