# Generated by Django 4.0.6 on 2022-07-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan', '0008_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myUser',
        ),
    ]
