# Generated by Django 4.0.6 on 2022-07-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan', '0011_pembukuan_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembukuan',
            old_name='category_id',
            new_name='categoryId',
        ),
    ]
