# Generated by Django 4.0.6 on 2022-07-13 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan', '0012_rename_category_id_pembukuan_categoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembukuan',
            name='categoryId',
        ),
        migrations.AlterField(
            model_name='pembukuan',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pembukuan.category'),
        ),
    ]
