# Generated by Django 4.0.6 on 2022-07-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan', '0013_remove_pembukuan_categoryid_alter_pembukuan_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembukuan',
            name='category',
        ),
    ]
