# Generated by Django 4.0.6 on 2022-07-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan', '0016_alter_details_options_remove_category_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={},
        ),
    ]
