# Generated by Django 4.0.5 on 2022-07-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    def insert_default_vendor(apps, schema_editor):
        Vendor = apps.get_model('produk', 'vendor')
        vendor_takde = Vendor(name='Tidak Ada')
        vendor_takde.save()

    operations = [
        migrations.RunPython(insert_default_vendor)
    ]
