# Generated by Django 4.0.5 on 2022-07-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name_plural': 'Vendors'},
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendoraddress',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendorname',
        ),
    ]
