# Generated by Django 4.0.6 on 2022-07-12 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan', '0005_pembukuan_company'),
        ('produk', '0002_auto_20220710_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pembukuan.details'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pembukuan.details'),
        ),
    ]
