# Generated by Django 4.0.5 on 2022-07-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_alter_vendor_options_rename_vendor_vendor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='produk',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
