# Generated by Django 4.0.6 on 2022-07-13 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_produk_vend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='vend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produk.vendor'),
        ),
    ]
